# Generated by Django 4.2.2 on 2023-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_add_question_option_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_question',
            name='correct_answer',
            field=models.CharField(default='الاجابة الصحيحة ', max_length=100),
        ),
        migrations.AddField(
            model_name='add_question',
            name='option_1',
            field=models.CharField(default='الاخيار الاول ', max_length=100),
        ),
        migrations.AddField(
            model_name='add_question',
            name='option_2',
            field=models.CharField(default='الاخيار الثاني ', max_length=100),
        ),
        migrations.AddField(
            model_name='add_question',
            name='option_3',
            field=models.CharField(default='الاخيار الثالث ', max_length=100),
        ),
        migrations.AddField(
            model_name='add_question',
            name='option_4',
            field=models.CharField(default='الاخيار الرابع ', max_length=100),
        ),
        migrations.AlterField(
            model_name='add_question',
            name='question',
            field=models.TextField(default='نص السؤال ', max_length=1500),
        ),
    ]
