# Generated by Django 4.2.2 on 2023-06-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_add_question_correct_answer_add_question_option_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_question',
            new_name='question',
        ),
    ]
